"""add users

Revision ID: 38c2c8e3f69c
Revises: 99eaed046d00
Create Date: 2025-12-10 12:09:46.771495

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c2c8e3f69c'
down_revision = '99eaed046d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_building_id', table_name='devices')
    op.drop_index('ix_devices_code', table_name='devices')
    op.drop_index('ix_devices_floor_id', table_name='devices')
    op.drop_index('ix_devices_floor_plan_id', table_name='devices')
    op.drop_index('ix_devices_id', table_name='devices')
    op.drop_index('ix_devices_mac_address', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_buildings_code', table_name='buildings')
    op.drop_index('ix_buildings_id', table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('ix_alert_events_building_id', table_name='alert_events')
    op.drop_index('ix_alert_events_device_id', table_name='alert_events')
    op.drop_index('ix_alert_events_floor_id', table_name='alert_events')
    op.drop_index('ix_alert_events_floor_plan_id', table_name='alert_events')
    op.drop_index('ix_alert_events_group_id', table_name='alert_events')
    op.drop_index('ix_alert_events_id', table_name='alert_events')
    op.drop_index('ix_alert_events_person_id', table_name='alert_events')
    op.drop_index('ix_alert_events_rule_id', table_name='alert_events')
    op.drop_index('ix_alert_events_tag_id', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_people_document_id', table_name='people')
    op.drop_index('ix_people_id', table_name='people')
    op.drop_table('people')
    op.drop_index('ix_person_groups_id', table_name='person_groups')
    op.drop_table('person_groups')
    op.drop_index('ix_incidents_closed_at', table_name='incidents')
    op.drop_index('ix_incidents_device_event_id', table_name='incidents')
    op.drop_index('ix_incidents_device_id', table_name='incidents')
    op.drop_index('ix_incidents_device_id_status', table_name='incidents')
    op.drop_index('ix_incidents_due_at', table_name='incidents')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_status_severity_created_at', table_name='incidents')
    op.drop_index('ix_incidents_tenant', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_collection_logs_device_id', table_name='collection_logs')
    op.drop_index('ix_collection_logs_id', table_name='collection_logs')
    op.drop_index('ix_collection_logs_tag_id', table_name='collection_logs')
    op.drop_table('collection_logs')
    op.drop_index('ix_device_topics_device_id', table_name='device_topics')
    op.drop_index('ix_device_topics_id', table_name='device_topics')
    op.drop_table('device_topics')
    op.drop_index('ix_floors_building_id', table_name='floors')
    op.drop_index('ix_floors_id', table_name='floors')
    op.drop_table('floors')
    op.drop_index('ix_device_events_analytic_type', table_name='device_events')
    op.drop_index('ix_device_events_device_id', table_name='device_events')
    op.drop_index('ix_device_events_id', table_name='device_events')
    op.drop_index('ix_device_events_occurred_at', table_name='device_events')
    op.drop_index('ix_device_events_topic', table_name='device_events')
    op.drop_table('device_events')
    op.drop_table('person_group_memberships')
    op.drop_index('ix_floor_plans_floor_id', table_name='floor_plans')
    op.drop_index('ix_floor_plans_id', table_name='floor_plans')
    op.drop_table('floor_plans')
    op.drop_index('ix_tags_id', table_name='tags')
    op.drop_index('ix_tags_mac_address', table_name='tags')
    op.drop_index('ix_tags_person_id', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_webhook_subscriptions_id', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index('ix_incident_messages_created_at', table_name='incident_messages')
    op.drop_index('ix_incident_messages_incident_id', table_name='incident_messages')
    op.drop_table('incident_messages')
    op.drop_index('ix_alert_rules_device_id', table_name='alert_rules')
    op.drop_index('ix_alert_rules_group_id', table_name='alert_rules')
    op.drop_index('ix_alert_rules_id', table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('alert_rules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('rule_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_dwell_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='alert_rules_device_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['person_groups.id'], name='alert_rules_group_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='alert_rules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_alert_rules_id', 'alert_rules', ['id'], unique=False)
    op.create_index('ix_alert_rules_group_id', 'alert_rules', ['group_id'], unique=False)
    op.create_index('ix_alert_rules_device_id', 'alert_rules', ['device_id'], unique=False)
    op.create_table('incident_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=32), server_default=sa.text("'TEXT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_thumb_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='incident_messages_incident_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='incident_messages_pkey')
    )
    op.create_index('ix_incident_messages_incident_id', 'incident_messages', ['incident_id'], unique=False)
    op.create_index('ix_incident_messages_created_at', 'incident_messages', ['created_at'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('secret_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_type_filter', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='webhook_subscriptions_pkey')
    )
    op.create_index('ix_webhook_subscriptions_id', 'webhook_subscriptions', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tags_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('mac_address', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='tags_person_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tags_person_id', 'tags', ['person_id'], unique=False)
    op.create_index('ix_tags_mac_address', 'tags', ['mac_address'], unique=True)
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    op.create_table('floor_plans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('floor_plans_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('floor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('width', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name='floor_plans_floor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='floor_plans_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_floor_plans_id', 'floor_plans', ['id'], unique=False)
    op.create_index('ix_floor_plans_floor_id', 'floor_plans', ['floor_id'], unique=False)
    op.create_table('person_group_memberships',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['person_groups.id'], name='person_group_memberships_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='person_group_memberships_person_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', 'group_id', name='person_group_memberships_pkey')
    )
    op.create_table('device_events',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('device_events_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('analytic_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='device_events_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='device_events_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_device_events_topic', 'device_events', ['topic'], unique=False)
    op.create_index('ix_device_events_occurred_at', 'device_events', ['occurred_at'], unique=False)
    op.create_index('ix_device_events_id', 'device_events', ['id'], unique=False)
    op.create_index('ix_device_events_device_id', 'device_events', ['device_id'], unique=False)
    op.create_index('ix_device_events_analytic_type', 'device_events', ['analytic_type'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('floors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name='floors_building_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='floors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_floors_id', 'floors', ['id'], unique=False)
    op.create_index('ix_floors_building_id', 'floors', ['building_id'], unique=False)
    op.create_table('device_topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kind', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='device_topics_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='device_topics_pkey')
    )
    op.create_index('ix_device_topics_id', 'device_topics', ['id'], unique=False)
    op.create_index('ix_device_topics_device_id', 'device_topics', ['device_id'], unique=False)
    op.create_table('collection_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rssi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw_payload', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='collection_logs_device_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='collection_logs_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='collection_logs_pkey')
    )
    op.create_index('ix_collection_logs_tag_id', 'collection_logs', ['tag_id'], unique=False)
    op.create_index('ix_collection_logs_id', 'collection_logs', ['id'], unique=False)
    op.create_index('ix_collection_logs_device_id', 'collection_logs', ['device_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.VARCHAR(length=64), server_default=sa.text("'CAMERA_ISSUE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'OPEN'::character varying"), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=32), server_default=sa.text("'MEDIUM'::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('sla_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_event_id'], ['device_events.id'], name='incidents_device_event_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='incidents_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='incidents_pkey')
    )
    op.create_index('ix_incidents_tenant', 'incidents', ['tenant'], unique=False)
    op.create_index('ix_incidents_status_severity_created_at', 'incidents', ['status', 'severity', 'created_at'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_due_at', 'incidents', ['due_at'], unique=False)
    op.create_index('ix_incidents_device_id_status', 'incidents', ['device_id', 'status'], unique=False)
    op.create_index('ix_incidents_device_id', 'incidents', ['device_id'], unique=False)
    op.create_index('ix_incidents_device_event_id', 'incidents', ['device_event_id'], unique=False)
    op.create_index('ix_incidents_closed_at', 'incidents', ['closed_at'], unique=False)
    op.create_table('person_groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('person_groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='person_groups_pkey'),
    sa.UniqueConstraint('name', name='person_groups_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_person_groups_id', 'person_groups', ['id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('people_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='people_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_people_id', 'people', ['id'], unique=False)
    op.create_index('ix_people_document_id', 'people', ['document_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('floor_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('floor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_open', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name='alert_events_building_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='alert_events_device_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name='alert_events_floor_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], name='alert_events_floor_plan_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['person_groups.id'], name='alert_events_group_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='alert_events_person_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name='alert_events_rule_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='alert_events_tag_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='alert_events_pkey')
    )
    op.create_index('ix_alert_events_tag_id', 'alert_events', ['tag_id'], unique=False)
    op.create_index('ix_alert_events_rule_id', 'alert_events', ['rule_id'], unique=False)
    op.create_index('ix_alert_events_person_id', 'alert_events', ['person_id'], unique=False)
    op.create_index('ix_alert_events_id', 'alert_events', ['id'], unique=False)
    op.create_index('ix_alert_events_group_id', 'alert_events', ['group_id'], unique=False)
    op.create_index('ix_alert_events_floor_plan_id', 'alert_events', ['floor_plan_id'], unique=False)
    op.create_index('ix_alert_events_floor_id', 'alert_events', ['floor_id'], unique=False)
    op.create_index('ix_alert_events_device_id', 'alert_events', ['device_id'], unique=False)
    op.create_index('ix_alert_events_building_id', 'alert_events', ['building_id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('buildings_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='buildings_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_buildings_id', 'buildings', ['id'], unique=False)
    op.create_index('ix_buildings_code', 'buildings', ['code'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('floor_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('building_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('floor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('mac_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('pos_x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pos_y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('shard', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('analytics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name='devices_building_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], name='devices_floor_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], name='devices_floor_plan_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='devices_pkey')
    )
    op.create_index('ix_devices_mac_address', 'devices', ['mac_address'], unique=True)
    op.create_index('ix_devices_id', 'devices', ['id'], unique=False)
    op.create_index('ix_devices_floor_plan_id', 'devices', ['floor_plan_id'], unique=False)
    op.create_index('ix_devices_floor_id', 'devices', ['floor_id'], unique=False)
    op.create_index('ix_devices_code', 'devices', ['code'], unique=True)
    op.create_index('ix_devices_building_id', 'devices', ['building_id'], unique=False)
    # ### end Alembic commands ###
